#! /bin/bash
# getopt1:
# Sample script using the function getopt
#
# Type something like "getopt1 -ab -d 10 -e20 text1 text2"
# on the command line to see how it works
#
# See getopt.sh for more information
. getopt.sh
echo Using getopt to parse arguments:
while getopt "abcd:e." "$@"
do
  echo "Option <$OPTOPT> ${OPTARG:+has an arg <$OPTARG>}"
done
shift $[OPTIND-1]
for arg in "$@"
do
  echo "Non option argument <$arg>"
done

